[<EntryPoint>]
let main _ =

    //Day01.show ()
    Day02.show ()
    //Day03.show ()
    //Day04.show ()
    Day05.show ()
    //Day06.show ()
    //Day07.show ()
    //Day08.show ()
    //Day09.show ()
    //Day10.show ()
    //Day11.show ()
    //Day12.show ()
    //Day13.show ()
    //Day14.show ()
    //Day15.show ()
    //Day16.show ()
    //Day17.show ()
    //Day18.show ()
    //Day19.show ()
    //Day20.show ()
    //Day21.show ()
    //Day22.show ()
    //Day23.show ()
    //Day24.show ()
    //Day25.show ()

    0
